### ISSUE TITLE
Küçük düzeltme

### ISSUE THREAD

**Issue by anilburakgokce** [iltekin/musahit-testi#5]
Harika bir test olmuş, elinize sağlık. 
Bildiğim kadarıyla Seviye 6'nın 6. sorusunda (Leman Teyze'li soru) yakılan şeyler pusula değil zarf olmalı. sorudan sonra gelen genelge maddesinde de zarf diyor.
İyi Çalışmalar

**Comment by iltekin** [comment]
Düzelttik, teşekkür ederiz 🙏🏼
